name= "pastebin-worker"
compatibility_date = "2024-05-04"
account_id= "zn1PEOkEq5dFfrezZMt7ZRN9Z-UYGPae5tq9NTwD"
main = "src/index.ts"
workers_dev = false

# 如果没使用自定义域名，将BASE_URL改为 worker 的默认路由
vars = { ENVIRONMENT = "production", BASE_URL = "https://shiny-shape-e60a.ycxsw.workers.dev/" }

# 如果不使用自定义域名，将下面的代码注释掉
route = { pattern = "as.al", custom_domain = true }

kv_namespaces = [
  { binding = "txt", id = "182acf9bc9de45c8a41a4bde4bb49817" },
]

[site]
bucket = "./static/dist"


[[r2_buckets]]
binding = 'BUCKET'
bucket_name = '222'
